### ISSUE TITLE
`FilterCarSurvScore` and mlr3proba CRAN removal

### ISSUE THREAD

**Issue by sebffischer** [mlr-org/mlr3filters#131]
The proba Filter (CarSurvScore) has to be migrated for the next CRAN release. I guess mlr3proba? 
@RaphaelS1 @mllg

**Comment by pat-s** [comment]
It doesn't cause an error on CRAN as everything is escaped. It does not make a difference then if it lives here or in mlr3proba as users need mlr3proba anyhow. Hence I'd just keep it as it is?

**Comment by sebffischer** [comment]
Ok I didn't know that it is no problem for CRAN. I thought it might be when we make a new release but if you say it doesn't than I don't see any problems either :)

**Comment by pat-s** [comment]
Seems like we still need to migrate it as it will otherwise cause a note in the next release which prevents the submission.

I've had a little stab on trying to integrate some {mlr3proba} components into {mlr3filters} but I stopped after

- adding a dataset for the task required for the filter
- adding TaskSurv (needed for the dataset)
- adding multiple helpers for the task

That's too much non-filter stuff to add unfortunately.

I am not sure though if the filter can be easily migrated to proba as this would also mean porting many code from {mlr3filters} to {mlr3proba}.
It might be that we need to remove it?
Thoughts @mllg @be-marc @sebffischer?

**Comment by sebffischer** [comment]
can we make mlr3proba depend on mlr3filters? Than we can just add it there

**Comment by pat-s** [comment]
Also possible even though I am not sure @RaphaelS1 would like to do this?

In the end we might face this issue here on a more generic level in many mlr3 packages that {mlr3proba} interacts with, i.e. moving content to {mlr3proba} to keep it as we need to move {mlr3proba} things out for CRAN releases of the respective other packages.

This would in sum bloat {mlr3proba} quite a bit and at same point eventually force us to move everything back (if {mlr3proba} is back on CRAN eventually some day).

The alternative would be to remove the resource entirely (in this case the filter) which would cause disrupting for users in many places (viz, filters, etc.).

@RaphaelS1 What is your opinion on this? Also on the general problem, not only the specific one here with this one filter.

**Comment by RaphaelS1** [comment]
My general response to this is basically that as I'm making things harder by not being on CRAN, I'm happy for you guys to make the decision that is easiest for the rest of the packages.

**Comment by mllg** [comment]
I've removed the example. The filter and the test can in mlr3filters.

**Comment by pat-s** [comment]
I overlooked this easy solution, thanks Michel! Let's close here now as we have a good workaround.
