### ISSUE TITLE
Filter request: 'insignificant' factor levels

### ISSUE THREAD

**Issue by shudras** [mlr-org/mlr3filters#76]
Scarcely occurring factor levels can distort modeling results. A filter that removes or imputes 'insignificant' factor levels would help prevent this. Insignificance could be denoted as ratio between factor occurrence and total samples.

**Comment by pat-s** [comment]
We are not inventing new filters but only providing an interface to existing ones.

If there is a dedicated filter that has been reviewed and properly implemented in R, feel free to propose it here as a feature. 

Besides that, filter do not remove features but only rank them according to a certain heuristic.
If you are searching for algs that drop features by design, have a look at {mlr3fselect}.

**Comment by berndbischl** [comment]
@shudras also have a look at what mlr3pipelines provides in terms of factor preprocessing and factor encoding operations! that also is a potential solution to what you describe
